name: Validate JSON syntax
name: Validate JSON syntax

on:
  push:
    paths:
      - 'workflows/**/*.json'
  pull_request:
    paths:
      - 'workflows/**/*.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON syntax
        run: |
          find workflows/ -name "*.json" -exec jq empty {} \;
on:
  push:
    paths:
      - 'workflows/**/*.json'
  pull_request:
    paths:
      - 'workflows/**/*.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON syntax
        run: |
          find workflows/ -name "*.json" -exec jq empty {} \;
